// <auto-generated />
namespace HEJARITO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Efternyaändringarsomvi4gjorde : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Efternyaändringarsomvi4gjorde));
        
        string IMigrationMetadata.Id
        {
            get { return "201803121335361_Efter nya ändringar som vi 4 gjorde"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
