// <auto-generated />
namespace HEJARITO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialERDSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialERDSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201803080901093_initial ERD & Seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
